### ISSUE TITLE
关于lualib-profiler.c

### ISSUE THREAD

**Issue by linxiaolong** [findstr/silly#4]
1、该库对递归函数情况没处理也不兼容
2、看了项目代码，应该是没使用该库？

**Comment by findstr** [comment]
1. 递归确实不兼容，但是其实是处理了的，如果start和stop不是成对出现，其实是会报错的。
2. 为了简化实现实现，并没有支持递归。如果要测试递归只要把profiler范围放在最开始调用此函数处即可。
3. 有使用该库，但他毕竟只是一个性能分析器，正常的代码不会一直挂着性能分析器，你说呢呢。

**Comment by linxiaolong** [comment]
嗯，我这边需求是想所有函数都有所监控，看了下你代码发现应该是需要手动设置监测范围。

**Comment by findstr** [comment]
我第一版是可以的，后来觉得监控信息太多就重写了.

一个简单满足你需求的办法是，使用lua的debug库，hook函数的进入与推出。在进入时调用profiler.start推出时调用profiler.stop

**Comment by findstr** [comment]
我第一版是可以的，后来觉得监控信息太多就重写了.

一个简单满足你需求的办法是，使用lua的debug库，hook函数的进入与退出。在进入时调用profiler.start退出时调用profiler.stop，然后修改一下profiler使其支持多次start
