### ISSUE TITLE
偶现server接收不到数据

### ISSUE THREAD

**Issue by yfengworld** [findstr/silly#6]
测试环境：win10 linux子系统
使用sample里的sampled.lua和client.lua测试，偶现client可以连接上但是服务端报
[socket] checksocket sid:13 unsunpport type:0

**Comment by findstr** [comment]
unsunpport type:0代表，向此socket发送时，对端已经关闭了这个socket

**Comment by yfengworld** [comment]
嗯 后面看了下代码估计也是这个问题。请问你这套用在生产环境了吗

**Comment by findstr** [comment]
用了
