### ISSUE TITLE
base64encode有bug

### ISSUE THREAD

**Issue by yfengworld** [findstr/silly#8]
base64encode有bug，有些字符会成\

**Comment by findstr** [comment]
麻烦给个测试字符串，谢谢

**Comment by yfengworld** [comment]
测试字符串:9l84O7qcu1EHQpzcI+r2Wg==258EAFA5-E914-47DA-95CA-C5AB0DC85B11
先sha1,再base64,结果为/5QNizRT//+J//+cdSQt//+O5Bc=

**Comment by findstr** [comment]
'/’是正常字符集，'\'才是非法的。

**Comment by yfengworld** [comment]
我不是说‘/’不是正常字符集，我的意思是转码出来不对。我是接websocket的时候发现的。后面换成skynet里的base64了，上面的测试字符串，经过sha1再base64,结果为:x6Zx50uNyuHuAqnY2JkUEycLCSs=

**Comment by findstr** [comment]
应该没问题了~

**Comment by yfengworld** [comment]
经测试,ok了。方便给个qq吗，有时间交流一下

**Comment by findstr** [comment]
私信我邮件

**Comment by findstr** [comment]
我用邮箱给你发QQ号

**Comment by yfengworld** [comment]
github，qq交流------------------ 原始邮件 ------------------
发件人: "重归混沌"<notifications@github.com>
发送时间: 2019年4月22日(星期一) 下午4:36
收件人: "findstr/silly"<silly@noreply.github.com>;
抄送: "yfengworld"<449557841@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [findstr/silly] base64encode有bug (#8)



我用邮箱给你发QQ号
 
&mdash;
